### ISSUE TITLE
εμένα πάντως δεν με ενφανίζει 

### ISSUE THREAD

**Issue by jemadux** [eellak/greek-commiters#1]
τι λάθος έχω κάνει;;; ή έχετε κάνει ;;

**Comment by thanostx** [comment]
Γράφεις "Greeece" με τρία e στο προφίλ σου.

**Comment by Polichronucci** [comment]
Όπως λέει και ο @thanostx, το location που έχεις βάλει έχει 3 "e".

**Comment by jemadux** [comment]
ααα .. ευχαριστώ
